service_name: "api-sample"

environment: "development"

server:
    address: ":8080"
    write_timeout: "15s"
    read_timeout: "15s"
    idle_timeout: "1m"
    shutdown_timeout: "30s"

cors:
    allowed_headers: ["Authorization", "Content-Type", "*"]
    allowed_methods: ["PUT", "GET", "POST", "DELETE", "PATCH", "OPTIONS"]
    allowed_origins: ["*"]
    exposed_headers: ["PUT", "GET", "POST", "DELETE", "PATCH", "OPTIONS"]
    max_age: 1728000

databaseInfo:
    database: "api-sample" 
    host: "localhost"
    port: 5432
    user: "api"
    password: "Api@123"
    dialect: "postgres"
