basePath: /v1
definitions:
  models.ProductRequest:
    properties:
      discount:
        type: integer
      name:
        type: string
      price:
        type: number
    type: object
info:
  contact:
    name: GitHub
    url: https://www.github.com/joemersonsouza
  description: This is a sample RESTFULL API
  license:
    name: BSD License
  title: Boilerplate API in GO
  version: "1.0"
paths:
  /item:
    post:
      consumes:
      - application/json
      description: Add a new item
      parameters:
      - description: Item body
        in: body
        name: Item
        required: true
        schema:
          $ref: '#/definitions/models.ProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
        "400":
          description: Invalid body
          schema:
            type: string
        "500":
          description: Something goes wrong
          schema:
            type: string
      summary: Add a new item
  /item/:{id}:
    put:
      consumes:
      - application/json
      description: change an existing item
      parameters:
      - description: Item ID
        in: body
        name: id
        required: true
        schema:
          type: string
      - description: Item body
        in: body
        name: Item
        required: true
        schema:
          $ref: '#/definitions/models.ProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
        "400":
          description: Invalid body
          schema:
            type: string
        "404":
          description: Item not found
          schema:
            type: string
        "500":
          description: Something goes wrong
          schema:
            type: string
      summary: Change an item
  /item/{id}:
    get:
      consumes:
      - application/json
      description: get an item by ID
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Product Item
          schema:
            $ref: '#/definitions/models.ProductRequest'
        "404":
          description: Item not found
          schema:
            type: string
      summary: Get a specific item
  /items:
    get:
      consumes:
      - application/json
      description: get items
      produces:
      - application/json
      responses:
        "200":
          description: List of products
          schema:
            $ref: '#/definitions/models.ProductRequest'
        "204":
          description: No content
          schema:
            type: string
      summary: Get all stored items
swagger: "2.0"
